### ISSUE TITLE
tspdb crashing

### ISSUE THREAD

**Issue by avabarid** [AbdullahO/tspdb#5] opened 2021-05-09 01:12 UTC
Hi,
I have been testing tspdb on few datasets and noticed it crashes sometimes. It originally happens because calling create_pindex on a dataset throws:
  PL/Python function "create_pindex", line 268, in create_index  
  PL/Python function "create_pindex", line 309, in update_model 
  PL/Python function "create_pindex", line 140, in update_model 
  PL/Python function "create_pindex", line 238, in fitModels 
  PL/Python function "create_pindex", line 222, in fit 
  PL/Python function "create_pindex", line 119, in _computeWeights
  PL/Python function "create_pindex", line 77, in matrixFromSVD

Looking into it I realized it happens because in line 55 of algorithms/svdWrapper.py, you are returnig a list instead of datafram. so I changed it to:
return (np.array([]), np.array([]), np.array([]))

Then the error changes:
ERROR:  IndexError: invalid index to scalar variable.
CONTEXT:  Traceback (most recent call last):
  PL/Python function "create_pindex", line 18, in <module>
    TSPD.create_index()
  PL/Python function "create_pindex", line 268, in create_index
  PL/Python function "create_pindex", line 309, in update_model
  PL/Python function "create_pindex", line 140, in update_model
  PL/Python function "create_pindex", line 238, in fitModels
  PL/Python function "create_pindex", line 222, in fit
  PL/Python function "create_pindex", line 123, in _computeWeights
PL/Python function "create_pindex"

And this happens because in previous part returned empty dataframe. looking into why that line is executed, it is because k==0 (kSingularValue==0)

Then I traced back and it happens because in prediction_models/ts_svd_model.py fit function, this code:
        (self.sk, self.Uk, self.Vk) = svdMod.reconstructMatrix(self.kSingularValues, returnMatrix=False)
        if self.kSingularValues is None:
            self.kSingularValues= len(self.sk)
will change kSingularValues to 0 (somehow self.sk is 0)

That's where I stopped and could not check further.
If you want, I can send you my dataset to simulate the problem.

Thanks!

**Comment by AbdullahO** [comment] 2021-05-09 06:47
Thanks avabarid for your feedback. 

I suspect the issue is that the default method that selects the rank end up selecting sk =0, which is easily fixed by ensuring that the chosen rank is always >=1. 

I fixed that issue in the latest commit. Let me know if that fixes things. If it does not, we can take a closer look at the data and try to replicate the error.

Thanks

**Comment by avabarid** [comment] 2021-05-09 11:25
Hi Abdullah,

Let me check and I will get back to you.

 

Thanks!

**Comment by avabarid** [comment] 2021-05-09 17:35
I think your latest update fixed it! thank you.

**Closed** 2021-05-09 19:00 UTC
